training_pipeline_config:
  pipeline_name: shipment
  artifact_dir: artifact

data_ingestion_config:
  author_username : divyeshardeshana
  kaggel_dataset_name : supply-chain-shipment-pricing-data
  raw_data_dir: raw_data

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml

data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
