grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
    n_jobs : 5

model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: True
      n_jobs : 5

    search_param_grid:
      fit_intercept:
      - True
      - False

  module_1:
    class: Ridge
    module: sklearn.linear_model
    params:
      fit_intercept: True
      n_jobs : 5

    search_param_grid:
      fit_intercept:
        - True
        - False

  module_3:
    class: Lasso
    module: sklearn.linear_model
    params:
      fit_intercept: True
      n_jobs : 5

    search_param_grid:
      fit_intercept:
        - True
        - False
