grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
    n_jobs : 5

model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: True
      n_jobs : 5

    search_param_grid:
      fit_intercept:
      - True
      - False

  module_1:
    class: Ridge
    module: sklearn.linear_model
    params:
      fit_intercept: True
      n_jobs : 5

    search_param_grid:
      fit_intercept:
        - True
        - False

  module_3:
    class: Lasso
    module: sklearn.linear_model
    params:
      fit_intercept: True
      n_jobs : 5

    search_param_grid:
      fit_intercept:
        - True
        - False

  module_4:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 40
      min_samples_leaf: 2
      n_jobs : 5

    search_param_grid:
      n_estimators:
        - 5
        - 10
        - 20
      criterion:
        - squared_error
      max_depth:
        - 2
        - 5
      min_samples_split:
        - 2
        - 4
      min_samples_leaf:
        - 2
        - 4
        
