columns:
    ID: int64
    Project Code: O
    "PQ #": O
    "PO / SO #": O
    "ASN/DN #": O
    Country: O
    Managed By: O
    Fulfill Via: O
    Vendor INCO Term: O
    Shipment Mode: O
    PQ First Sent to Client Date: O
    PO Sent to Vendor Date: O
    Scheduled Delivery Date: O
    Delivered to Client Date: O
    Delivery Recorded Date: O
    Product Group: O
    Sub Classification: O
    Vendor: O
    Item Description: O
    Molecule/Test Type: O
    Brand: O
    Dosage: O
    Dosage Form: O
    Unit of Measure (Per Pack): int64
    Line Item Quantity: int64
    Line Item Value: float64
    Pack Price: float64
    Unit Price: float64
    Manufacturing Site: O
    First Line Designation: O
    Weight (Kilograms): O
    Freight Cost (USD): O
    Line Item Insurance (USD): float64

numerical_columns:
    - ID
    - Unit of Measure (Per Pack)
    - Line Item Quantity
    - Line Item Value
    - Line Item Insurance (USD)
    - Pack Price

categorical_columns:
    - Project Code
    - "PQ #"
    - "PO / SO #"
    - "ASN/DN #"
    - Country
    - Managed By
    - Fulfill Via
    - Vendor INCO Term
    - Shipment Mode
    - PQ First Sent to Client Date
    - PO Sent to Vendor Date
    - Scheduled Delivery Date
    - Delivered to Client Date
    - Delivery Recorded Date
    - Product Group
    - Sub Classification
    - Vendor
    - Item Description
    - Molecule/Test Type
    - Brand
    - Dosage
    - Dosage Form
    - Manufacturing Site
    - First Line Designation
    - Weight (Kilograms)
    - Freight Cost (USD)

target_column: Unit Price

number_of_column : 33