name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Install shipment dependencies 
      run: |
        $CONDA/bin/conda install --file requirements.txt
    - name: clone demo script
      run: git clone https://github.com/Mayankgaj/demo_script.git --depth=1 demo
    - name: clone scorce
      run: git clone https://github.com/Mayankgaj/shipment_pricing_prediction.git --depth=1 shipment
           mv ./demo/*.py ./shipment
           $CONDA/bin/conda python demo.py
